Get devices for measurement successfully!
#### # Linerar 192 4096 16384
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
#### Find tuned kernel, pass
------------make_jit_kernel@factory.py-----------------
objective_func:fastest
-----------------make_kernel@ModuleBase---------------------
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
-----------init@HorizFusedKernel-------------
-------------initialize@HorizFusedKernel-------------
self.device_args['placeholder_0, placeholder1_0, T_matmul_NT_0', 'placeholder_1, placeholder1_1, T_matmul_NT_1']
self.shm_sizes[8192]
self.min_blocks_per_sm:1
self.blockidx_x:2048
-----------------get_code@GlobalKernel---------------------
--------------------------------------
processed_template_fname:/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/kernel_template/processed_Linear__in.cu
-------------generate_kernel@CUDACompiler---------------
-------------global@CUDACompiler---------------
kernel_type:horiz_fuse
__ctx__0
Traceback (most recent call last):
  File "linear_4096_16384.py", line 116, in <module>
    linear_kernel(x, weight, y)
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 22, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: (tensor([[ 0.1678, -1.7568,  0.4101,  ..., -0.1194, -1.4168,  0.3367],
        [-0.8732, -0.1595,  0.5943,  ..., -0.8851, -0.1336, -0.4201],
        [ 0.1609,  0.8533, -0.7862,  ..., -0.6442, -2.2728,  0.4570],
        ...,
        [ 0.4376, -0.5093, -1.6204,  ...,  0.0188,  0.5514,  0.8709],
        [-0.6542,  1.0992, -0.1363,  ..., -0.0847, -0.4171,  1.3058],
        [-0.9167, -0.9772,  0.0858,  ...,  0.7442, -0.0898,  0.7211]],
       device='cuda:0'), [Parameter containing:
tensor([[ 0.0126,  0.0039, -0.0116,  ...,  0.0148, -0.0143,  0.0063],
        [ 0.0116, -0.0093, -0.0126,  ..., -0.0077, -0.0026, -0.0028],
        [-0.0136,  0.0111,  0.0039,  ...,  0.0099, -0.0119, -0.0029],
        ...,
        [ 0.0095,  0.0065, -0.0089,  ...,  0.0146,  0.0116, -0.0096],
        [-0.0080, -0.0117,  0.0067,  ...,  0.0102,  0.0096, -0.0155],
        [-0.0092,  0.0029,  0.0110,  ..., -0.0094, -0.0126, -0.0010]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0126,  0.0039, -0.0116,  ...,  0.0148, -0.0143,  0.0063],
        [ 0.0116, -0.0093, -0.0126,  ..., -0.0077, -0.0026, -0.0028],
        [-0.0136,  0.0111,  0.0039,  ...,  0.0099, -0.0119, -0.0029],
        ...,
        [ 0.0095,  0.0065, -0.0089,  ...,  0.0146,  0.0116, -0.0096],
        [-0.0080, -0.0117,  0.0067,  ...,  0.0102,  0.0096, -0.0155],
        [-0.0092,  0.0029,  0.0110,  ..., -0.0094, -0.0126, -0.0010]],
       device='cuda:0', requires_grad=True)], tensor([[ 0.3744,  0.0695,  0.8983,  ...,  0.3564,  0.7304, -1.3010],
        [-0.8959, -1.2342, -1.0007,  ...,  1.1354,  0.1042, -0.5714],
        [-0.1810, -0.1512,  0.5945,  ...,  0.0989,  0.5227,  1.8946],
        ...,
        [-0.7678, -0.1375,  2.1278,  ..., -0.4564, -0.0944,  0.9420],
        [ 2.7145, -0.1334,  0.6983,  ...,  0.3826,  1.3548, -0.5083],
        [-1.9235, -0.1228,  0.2000,  ..., -0.5622, -2.5463, -1.0900]],
       device='cuda:0')), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7fe4dc30ba60>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7fe442ca4700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7fe596d12f70>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
