Get devices for measurement successfully!
#### # Linerar 192 4096 16384
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
#### Find tuned kernel, pass
type(x)<class 'list'>
type(y)<class 'list'>
type(linear.weight)<class 'torch.nn.parameter.Parameter'>
----------------make_jit_kernel@linear_4096.py-----------------
------------make_jit_kernel@factory.py-----------------
objective_func:fastest
-----------------make_kernel@ModuleBase---------------------
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
-----------init@HorizFusedKernel-------------
-------------initialize@HorizFusedKernel-------------
self.device_args['placeholder_0, placeholder1_0, T_matmul_NT_0', 'placeholder_1, placeholder1_1, T_matmul_NT_1']
self.shm_sizes[8192]
self.min_blocks_per_sm:1
self.blockidx_x:2048
-----------------get_code@GlobalKernel---------------------
--------------------------------------
processed_template_fname:/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/kernel_template/processed_Linear__in.cu
-------------generate_kernel@CUDACompiler---------------
-------------global@CUDACompiler---------------
kernel_type:horiz_fuse
__ctx__0
----------------execute_kernel@linear_4096.py-----------------
Traceback (most recent call last):
  File "linear_4096_16384.py", line 118, in <module>
    model(x,[linear.weight,linear.weight],1)
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 22, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: ([tensor([[ 1.6860, -0.1523,  1.0178,  ...,  0.3051,  0.3666,  1.0566],
        [-1.8320,  0.6985,  1.2170,  ...,  1.1078, -0.3174,  0.2673],
        [-0.3825, -0.9279,  0.4631,  ..., -0.1121, -0.2002,  1.0731],
        ...,
        [ 1.7462, -0.6401, -0.6321,  ...,  1.5622, -1.6361,  1.0556],
        [ 0.7048, -1.0967, -0.1928,  ...,  0.1954,  0.1540,  0.5811],
        [-0.5711, -0.8574, -0.0529,  ...,  0.3727, -1.7707,  0.9479]],
       device='cuda:0'), tensor([[ 1.6860, -0.1523,  1.0178,  ...,  0.3051,  0.3666,  1.0566],
        [-1.8320,  0.6985,  1.2170,  ...,  1.1078, -0.3174,  0.2673],
        [-0.3825, -0.9279,  0.4631,  ..., -0.1121, -0.2002,  1.0731],
        ...,
        [ 1.7462, -0.6401, -0.6321,  ...,  1.5622, -1.6361,  1.0556],
        [ 0.7048, -1.0967, -0.1928,  ...,  0.1954,  0.1540,  0.5811],
        [-0.5711, -0.8574, -0.0529,  ...,  0.3727, -1.7707,  0.9479]],
       device='cuda:0')], [Parameter containing:
tensor([[ 0.0023, -0.0013, -0.0111,  ..., -0.0027, -0.0052, -0.0007],
        [ 0.0006,  0.0038, -0.0087,  ..., -0.0051, -0.0124,  0.0149],
        [ 0.0050,  0.0139,  0.0143,  ...,  0.0006, -0.0064,  0.0132],
        ...,
        [-0.0078, -0.0089,  0.0096,  ...,  0.0026, -0.0116, -0.0092],
        [ 0.0099,  0.0021, -0.0027,  ..., -0.0086,  0.0152,  0.0116],
        [ 0.0121,  0.0102,  0.0108,  ...,  0.0038,  0.0136,  0.0005]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0023, -0.0013, -0.0111,  ..., -0.0027, -0.0052, -0.0007],
        [ 0.0006,  0.0038, -0.0087,  ..., -0.0051, -0.0124,  0.0149],
        [ 0.0050,  0.0139,  0.0143,  ...,  0.0006, -0.0064,  0.0132],
        ...,
        [-0.0078, -0.0089,  0.0096,  ...,  0.0026, -0.0116, -0.0092],
        [ 0.0099,  0.0021, -0.0027,  ..., -0.0086,  0.0152,  0.0116],
        [ 0.0121,  0.0102,  0.0108,  ...,  0.0038,  0.0136,  0.0005]],
       device='cuda:0', requires_grad=True)], 1), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7f2b2c097a60>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7f2a94298700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7f2be8302f70>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
